from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from transformers import pipeline
from intent_router import get_intent, get_optimized_prompt
from pyjsparser import parse
from pyjsparser.pyjsparserdata import JsSyntaxError
import google.generativeai as genai
import os
from dotenv import load_dotenv

# 🌟 Load variables from .env file
load_dotenv()

app = FastAPI()

# CORS configuration
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# SETUP 1: LOCAL SLM (YOUR MAIN THESIS PROJECT)

print("Loading Local CodeGen Model... Please wait...")
generator = pipeline(
    "text-generation",
    model="Salesforce/codegen-350M-mono",
    device=-1
)

def clean_code(generated_text, formatted_prompt):
    code = generated_text.replace(formatted_prompt, "")
    func_signature = formatted_prompt.split("\n")[-1]
    code = func_signature + code
    if "}" in code:
        code = code.split("}")[0] + "\n}"
    return code.strip()

def is_valid_javascript(code):
    try:
        parse(code)
        return True, "Code is valid"
    except JsSyntaxError as e:
        return False, str(e)
    except Exception as e:
        return False, "Unknown parsing error"


# SETUP 2: CLOUD AI (GEMINI)

gemini_api_key = os.getenv("GOOGLE_API_KEY")
genai.configure(api_key=gemini_api_key)

print("🔍 Searching for valid Gemini models...")
available_model = None
try:
    for m in genai.list_models():
        if 'generateContent' in m.supported_generation_methods:
            if 'gemini' in m.name.lower():
                available_model = m.name
                if 'flash' in m.name.lower():
                    break

    if available_model:
        print(f"✅ Successfully connected to: {available_model}")
        gemini_model = genai.GenerativeModel(available_model)
    else:
        print("❌ Warning: No valid Gemini model found.")
except Exception as e:
    print(f"❌ Gemini Setup Error: {e}")


# API ENDPOINT ROUTER

class PromptRequest(BaseModel):
    prompt: str
    mode: str = "local" # Default is your thesis logic

@app.post("/generate-code")
async def generate_code(request: PromptRequest):
    user_input = request.prompt
    
    
    # ENGINE 1: GEMINI CLOUD
 
    if request.mode == "gemini":
        try:
            structured_prompt = f"Write only valid JavaScript code for this request. No markdown, no explanations. Request: {user_input}"
            response = gemini_model.generate_content(structured_prompt)
            return {
                "user_input": user_input,
                "detected_intent": "Cloud Orchestration",
                "generated_code": response.text.strip().replace('```javascript', '').replace('```', ''),
                "attempts_taken": 1,
                "success": True,
                "debug_errors": []
                
            }
        except Exception as e:
            return {"generated_code": f"Gemini API Error: {str(e)}", "attempts_taken": 0, "success": False, "debug_errors": [str(e)]}

  
    # ENGINE 2: LOCAL AST SELF-HEALING LOOP (MAIN PROJECT)
  
    else:
        detected_intent = get_intent(user_input)
        formatted_prompt = get_optimized_prompt(user_input, detected_intent)

        max_retries = 3  
        final_code = ""
        is_successful = False
        error_log = []

        for attempt in range(max_retries):
            print(f"🔄 Local Attempt {attempt + 1} of {max_retries}...")
            
            # 1. Generate using CodeGen-350M
            result = generator(
                formatted_prompt,
                max_new_tokens=128,
                temperature=0.2 + (attempt * 0.1), 
                do_sample=True,
                pad_token_id=50256,
                truncation=True
            )

            raw_output = result[0]["generated_text"]
            
            # 2. Clean the output
            cleaned_code = clean_code(raw_output, formatted_prompt)

            # 3. Validate using AST Gatekeeper
            is_valid, error_msg = is_valid_javascript(cleaned_code)

            if is_valid:
                final_code = cleaned_code
                is_successful = True
                print("✅ Valid code generated by Local SLM!")
                break 
            else:
                print(f"❌ Local Attempt {attempt + 1} Failed: {error_msg}")
                error_log.append(f"Attempt {attempt + 1}: {error_msg}")

        if not is_successful:
            final_code = "// Error: AI could not generate valid syntax after 3 attempts.\n// Please try a simpler prompt."

        return {
            "user_input": user_input,
            "detected_intent": detected_intent,
            "generated_code": final_code,
            "attempts_taken": attempt + 1,      
            "success": is_successful,
            "debug_errors": error_log,
            "engine_used": "CodeGen-350M Local + AST"
        }